name: nerfstudio-env

channels:
  - defaults
  - nvidia/label/cuda-11.8.0

dependencies:
  - pip
  - setuptools
  - python=3.8
  - cuda-toolkit

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.0.1+cu118
      - torchvision==0.15.2+cu118
      - ninja
      - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
